### PR TITLE
issue77

### LINKED ISSUE #77: Replace Dot\Log\Exception\InvalidArgumentException
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 5.x

#### Summary

Replace usage of Dot\Log\Exception\InvalidArgumentException with Psr\Log\InvalidArgumentException

According to [PSR-3](https://www.php-fig.org/psr/psr-3/), the [`log` method](https://github.com/dotkernel/dot-log/blob/aaf3967f6a0e721dd021802965e431277c89836c/src/Logger.php#L359) must throw the exception from the psr.

The [current exception](https://github.com/dotkernel/dot-log/blob/aaf3967f6a0e721dd021802965e431277c89836c/src/Exception/InvalidArgumentException.php) is also used in other parts of the package, [such as in the filters](https://github.com/dotkernel/dot-log/blob/aaf3967f6a0e721dd021802965e431277c89836c/src/Filter/Regex.php#L7), but I see no reason why the PSR one couldn't be used there as well. In that case the current class could be removed

### PR DESCRIPTION
**Pull request by Jurj-Bogdan**
Removed `src/Exception/InvalidArgumentException.php` and replaced it's usage with `Psr\Log\InvalidArgumentException`.

Closes #77

### CODE REVIEW

**Comment by Jurj-Bogdan** [comment]
To adhere to PSR-3, only the `log` method from `Logger.php` must throw `Psr\Log\InvalidArgumentException`, but it felt confusing to keep the older one as well. Let me know if that would've been preferable though

**Review by alexmerlin — COMMENTED** [review]
IMO, I would keep `src/Exception/InvalidArgumentException.php`, because this was the purpose of having our own version of an exception: we can introduce modifications in the package, but the implementors do not need to adapt their code, they can continue using `Dot\Log\Exception\InvalidArgumentException`.
Keeping that file, you can undo almost the entire PR and you'll probably have end up having one single file modified.

File: src/Logger.php [hunk 1]
```diff
@@ -347,7 +348,7 @@ public function log(mixed $level, string|Stringable $message, iterable $context
         }
 
         if (($level < 0) || ($level >= count($this->levels))) {
-            throw new InvalidArgumentException(sprintf(
+            throw new PsrInvalidArgumentException(sprintf(
```
Comment (alexmerlin) [inline src/Logger.php]: Revert this, because we should use `Dot\Log\Exception\InvalidArgumentException`.

File: src/Logger.php [hunk 2]
```diff
@@ -19,6 +19,7 @@
 use Laminas\Stdlib\SplPriorityQueue;
 use Psr\Container\ContainerExceptionInterface;
 use Psr\Log\AbstractLogger;
+use Psr\Log\InvalidArgumentException as PsrInvalidArgumentException;
```
Comment (alexmerlin) [inline src/Logger.php]:
```suggestion
```

File: test/LoggerTest.php [hunk 3]
```diff
@@ -19,6 +18,7 @@
 use Laminas\Stdlib\SplPriorityQueue;
 use PHPUnit\Framework\TestCase;
 use Psr\Container\ContainerExceptionInterface;
+use Psr\Log\InvalidArgumentException;
```
Comment (alexmerlin) [inline test/LoggerTest.php]:
```suggestion
```

File: test/LoggerTest.php [hunk 4]
```diff
@@ -5,7 +5,6 @@
 namespace DotTest\Log;
 
 use ArrayObject;
-use Dot\Log\Exception\InvalidArgumentException;
```
Comment (alexmerlin) [inline test/LoggerTest.php]: Revert this.

**Review by alexmerlin — CHANGES_REQUESTED** [review]
Also, modify **src/Exception/InvalidArgumentException.php**:

```php
<?php

declare(strict_types=1);

namespace Dot\Log\Exception;

class InvalidArgumentException extends \Psr\Log\InvalidArgumentException
{
}
```
This is what I meant in my previous review.
Now that `Dot\Log\Exception\InvalidArgumentException` extends `Psr\Log\InvalidArgumentException`, which extends `\InvalidArgumentException` we can use our own `InvalidArgumentException` everywhere because it is an instance of all the exteded classes so it will be accepted everywhere.

**Comment by alexmerlin** [comment]
As I mentioned in my first review:

> Keeping that file, you can undo almost the entire PR and you'll probably have end up having one single file modified.

👍

**Review by alexmerlin — APPROVED** [review]
